### ISSUE TITLE
Message button in Agent Console not working properly in Safari 9.0.1

### ISSUE THREAD

**Issue by luacolin** [eztax-io/eztax-web#101]
![image](https://user-images.githubusercontent.com/7934195/47261342-34b55d80-d519-11e8-8462-e9c403aafd66.png)

When logged in as an Agent, the message button does not work. It brings you to an empty page when clicked. The function works in Chrome on the same machine, and also in Safari on a different machine. The version of the Safari browser is 9.0.1.

**Comment by superopengl** [comment]
Fixed.
