### ISSUE TITLE
Client dashboard page

### ISSUE THREAD

**Issue by superopengl** [eztax-io/eztax-web#16]
After a client logged in, the / route should change to the client dashboard page with

- A grid listing all lodgments that this client created.
- A button of `New lodgment` by clicking which will go to the create lodgment page.
- A grid listing all messages.
  - unread ones are bold.
  - read ones are normal.
- A button of `Message to admin` by clicking which will send message to admin.

**Comment by omartal** [comment]
Maybe we should add unread messages list as well on the dashboard.

**Comment by superopengl** [comment]
Good point. Will change the description.

**Comment by superopengl** [comment]
Will be included in other tickets.
