### ISSUE TITLE
Simplify wording on the homepage

### ISSUE THREAD

**Issue by superopengl** [eztax-io/eztax-web#37]
Current phrases on the homepage are too long to attract people to read. Need to make them shorter.

**Comment by luacolin** [comment]
Selling Points

**Qualified**
All our accountants are qualified and experienced. Many are members of CPAA, IPAA, NTAA and are Registered Tax Agents with the ATO.

**Convenient**
Eztax.io is convenient on another level: Just signup, shoot your documents, and submit. Our accountants will do the hard yards for you.

**Maximum Refund**
Our dedicated professionals have one sole objective when preparing your return that is to get you the maximum refund or pay minimum tax.

I think the rest of the text should remain the same. What do you think?

**Comment by superopengl** [comment]
Looks good to me. Thank you. Way simpler. Will reflect to the code now.
