### ISSUE TITLE
Phrasing the pages

### ISSUE THREAD

**Issue by superopengl** [eztax-io/eztax-web#9]
Phrase all texts on the public pages, like catch phrases, about us, pricing, for agents, and so forth.

**Comment by luacolin** [comment]
**About us**
We are a group of tech savvy accountants and programmers who set out to simplify the tax preparation experience for the taxpayer. We aim to not only to connect taxpayers with qualified tax accountants, but also be the first port of call for both taxpayers and accountants when it comes to tax. We are tax simplified.

**Pricing**
eztax.io is extremely competitive in terms of pricing, and prices for a simple return starts from a base of $59. For this reasonable price, you get access to a qualified tax accountant, who is able to utilise his/her expertise to give you the peace of mind that your tax return is in good hands.

**For Agents**
eztax.io is a hassle free platform for you to connect with the everyday taxpayer who is in need of your expertise. There is no need for a sales pitch to convince the taxpayer to utilise your services, as they are there to do business with you. You will be able to increase your fee bank without the cost normally associated with advertising and marketing, and be profitable from day one! 

**Catch phrase**
Tax simplified
